name: better_bus_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0
  http: ^1.2.2
  latlong2: ^0.9.1
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  archive: ^3.6.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  test_descriptor: ^2.0.2
